<h3 align="center" style="color:rgb(1, 126, 250);"><b>NORMALIZATION (Min - Max Scaling)</b></h3>

> **Goal:** Rescale numerical features to a fixed range, usually `0` to `1`.

##### Formula

$$X' = \frac{X-X_{\min}}{X_{\max}-X_{\min}}$$

##### Scikit-learn

```python
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
```

##### When to Use
- Features have different ranges.
- A fixed range such as `0–1` is desirable.
- Common examples: **KNN, Neural Networks, distance-based algorithms**.

##### Remember
- Sensitive to outliers because extreme values affect the minimum and maximum.
- Does not make data normally distributed.
- Fit on training data only; transform test data using the same scaler.
- Unlike standardization, it does not aim for mean `0` and standard deviation `1`.

In [1]:
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv("../00_datasets/housing.csv")

In [3]:
df.sample(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
7786,-118.05,33.90,36.0,1047.0,227.0,975.0,239.0,3.1897,155000.0,<1H OCEAN
16131,-122.48,37.79,52.0,4683.0,1055.0,2246.0,975.0,4.1148,457800.0,NEAR BAY
17838,-121.90,37.44,4.0,1646.0,408.0,853.0,410.0,5.0821,265500.0,<1H OCEAN
8445,-118.37,33.91,35.0,1742.0,283.0,812.0,282.0,5.6704,303700.0,<1H OCEAN
8889,-118.50,34.03,32.0,6365.0,1784.0,2767.0,1698.0,3.6451,383300.0,<1H OCEAN

In [4]:
columns = ["median_income", "total_rooms", "population"]

X = df[columns]

X.head()

   median_income  total_rooms  population
0         8.3252        880.0       322.0
1         8.3014       7099.0      2401.0
2         7.2574       1467.0       496.0
3         5.6431       1274.0       558.0
4         3.8462       1627.0       565.0

In [5]:
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(
    X_scaled,
    columns=columns,
    index=X.index
)

X_scaled.head()

   median_income  total_rooms  population
0       0.539668     0.022331    0.008941
1       0.538027     0.180503    0.067210
2       0.466028     0.037260    0.013818
3       0.354699     0.032352    0.015555
4       0.230776     0.041330    0.015752

In [6]:
scaler.fit_transform(X)

array([[0.53966842, 0.02233074, 0.00894083],
       [0.53802706, 0.18050257, 0.0672104 ],
       [0.46602805, 0.03726029, 0.01381765],
       ...,
       [0.08276438, 0.05727657, 0.0281398 ],
       [0.09429525, 0.04725571, 0.02068444],
       [0.13025338, 0.07078183, 0.03879032]], shape=(20640, 3))

In [7]:
print("Original data:")
print(X.head())

Original data:
   median_income  total_rooms  population
0         8.3252        880.0       322.0
1         8.3014       7099.0      2401.0
2         7.2574       1467.0       496.0
3         5.6431       1274.0       558.0
4         3.8462       1627.0       565.0

In [8]:
print("\nNormalized data:")
print(X_scaled.head())

Normalized data:
   median_income  total_rooms  population
0       0.539668     0.022331    0.008941
1       0.538027     0.180503    0.067210
2       0.466028     0.037260    0.013818
3       0.354699     0.032352    0.015555
4       0.230776     0.041330    0.015752

In [9]:
print("Minimum values learned:", scaler.data_min_)
print("Maximum values learned:", scaler.data_max_)
print("Feature ranges:", scaler.data_range_)

Minimum values learned: [0.4999 2.     3.    ]
Maximum values learned: [1.50001e+01 3.93200e+04 3.56820e+04]
Feature ranges: [1.45002e+01 3.93180e+04 3.56790e+04]