<h3 align="center" style="color:rgb(1, 126, 250);"><b>ORDINAL  ENCODING</b></h3>

> **Goal:** Convert categorical features into separate binary columns without implying an artificial ranking.

##### Example

| Weather | Rain | Snow | Sun |
| ------- | ---: | ---: | --: |
| Rain    |    1 |    0 |   0 |
| Snow    |    0 |    1 |   0 |
| Sun     |    0 |    0 |   1 |

##### Scikit-learn

```python
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

X_encoded = encoder.fit_transform(X)
```

##### When to Use

- Categories have no natural order.
- Examples: City, weather type, product category.
- Useful for nominal categorical input features.

##### Remember

- Creates a separate binary column for each category by default.
- Avoids assigning arbitrary numerical rankings to categories.
- `handle_unknown="ignore"` handles unseen categories during transformation.
- Can increase the number of features when a column has many unique categories.

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv("../00_datasets/seattle-weather.csv")

df.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1  2012-01-02           10.9      10.6       2.8   4.5     rain
2  2012-01-03            0.8      11.7       7.2   2.3     rain
3  2012-01-04           20.3      12.2       5.6   4.7     rain
4  2012-01-05            1.3       8.9       2.8   6.1     rain

In [2]:
df["weather"].value_counts()

weather
rain       641
sun        640
fog        101
drizzle     53
snow        26
Name: count, dtype: int64

In [3]:
X = df[["weather"]]

X.head()

   weather
0  drizzle
1     rain
2     rain
3     rain
4     rain

In [4]:
encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

X_encoded = encoder.fit_transform(X)

In [5]:
encoded_columns = encoder.get_feature_names_out(["weather"])

encoded_df = pd.DataFrame(
    X_encoded,
    columns=encoded_columns,
    index=X.index
)

encoded_df.head()

   weather_drizzle  weather_fog  weather_rain  weather_snow  weather_sun
0              1.0          0.0           0.0           0.0          0.0
1              0.0          0.0           1.0           0.0          0.0
2              0.0          0.0           1.0           0.0          0.0
3              0.0          0.0           1.0           0.0          0.0
4              0.0          0.0           1.0           0.0          0.0

In [6]:
print("Categories:", encoder.categories_)
print("Encoded shape:", encoded_df.shape)

encoded_df.sum()

Categories: [array(['drizzle', 'fog', 'rain', 'snow', 'sun'], dtype=object)]
Encoded shape: (1461, 5)

weather_drizzle     53.0
weather_fog        101.0
weather_rain       641.0
weather_snow        26.0
weather_sun        640.0
dtype: float64

In [7]:
pd.concat([X, encoded_df], axis=1).head()

,weather,weather_drizzle,weather_fog,weather_rain,weather_snow,weather_sun
0,drizzle,1.0,0.0,0.0,0.0,0.0
1,rain,0.0,0.0,1.0,0.0,0.0
2,rain,0.0,0.0,1.0,0.0,0.0
3,rain,0.0,0.0,1.0,0.0,0.0
4,rain,0.0,0.0,1.0,0.0,0.0