<h2 align="center" style="color: rgb(26, 91, 241);"><b>DATA QUALITY ASSESSMENT</b></h2>

In [ ]:
# IMPORT LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# LOAD THE DATASET

housing = pd.read_csv("housing.csv")

`Data Inspection`

In [4]:
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [7]:
housing.sample(5, random_state=42)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20046,-119.01,36.06,25.0,1505.0,NaN,1392.0,359.0,1.6812,47700.0,INLAND
3024,-119.46,35.14,30.0,2943.0,NaN,1565.0,584.0,2.5313,45800.0,INLAND
15663,-122.44,37.80,52.0,3830.0,NaN,1310.0,963.0,3.4801,500001.0,NEAR BAY
20484,-118.72,34.28,17.0,3051.0,NaN,1705.0,495.0,5.7376,218600.0,<1H OCEAN
9814,-121.93,36.62,34.0,2351.0,NaN,1063.0,428.0,3.7250,278000.0,NEAR OCEAN

In [8]:
housing.shape

(20640, 10)

In [10]:
housing.columns.to_list()

['longitude',
 'latitude',
 'housing_median_age',
 'total_rooms',
 'total_bedrooms',
 'population',
 'households',
 'median_income',
 'median_house_value',
 'ocean_proximity']

In [11]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [12]:
housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [13]:
housing.describe(include="all")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<1H OCEAN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9136
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909,NaN
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874,NaN
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000,NaN
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000,NaN
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000,NaN
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000,NaN
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000,NaN

`Data Quality Assessment`

In [15]:
missing = housing.isnull().sum()

In [20]:
print(missing)
missing[missing > 0]

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

total_bedrooms    207
dtype: int64

In [25]:
missing_pct = housing.isnull().mean() * 100
print(missing_pct)

missing_pct[missing_pct>0]

longitude             0.000000
latitude              0.000000
housing_median_age    0.000000
total_rooms           0.000000
total_bedrooms        1.002907
population            0.000000
households            0.000000
median_income         0.000000
median_house_value    0.000000
ocean_proximity       0.000000
dtype: float64

total_bedrooms    1.002907
dtype: float64

In [26]:
housing.isnull().sum().sum()

np.int64(207)

In [30]:
housing.duplicated().sum()

#IF DUPLICATES EXIST
# duplicates = housing[housing.duplicated()]

np.int64(0)

In [31]:
housing.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [34]:
housing.nunique().count

<bound method Series.count of longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64>

In [38]:
housing.nunique().sort_values()

ocean_proximity           5
housing_median_age       52
longitude               844
latitude                862
households             1815
total_bedrooms         1923
median_house_value     3842
population             3888
total_rooms            5926
median_income         12928
dtype: int64

In [42]:
housing["ocean_proximity"].value_counts(dropna=False)

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [44]:
missing_rows = housing[housing.isnull().any(axis=1)]
missing_rows.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
290,-122.16,37.77,47.0,1256.0,NaN,570.0,218.0,4.3750,161900.0,NEAR BAY
341,-122.17,37.75,38.0,992.0,NaN,732.0,259.0,1.6196,85100.0,NEAR BAY
538,-122.28,37.78,29.0,5154.0,NaN,3741.0,1273.0,2.5762,173400.0,NEAR BAY
563,-122.24,37.75,45.0,891.0,NaN,384.0,146.0,4.9489,247100.0,NEAR BAY
696,-122.10,37.69,41.0,746.0,NaN,387.0,161.0,3.9063,178400.0,NEAR BAY

In [46]:
len(missing_rows)

207

`Missing Bedrooms Count Investigation`

In [48]:
housing["bedrooms_missing"] = housing["total_bedrooms"].isnull()

comparison = housing.groupby("bedrooms_missing")[
    [
        "median_income",
        "total_rooms",
        "population",
        "households",
        "median_house_value"
    ]
].mean().round(2)

comparison

,median_income,total_rooms,population,households,median_house_value
bedrooms_missing,,,,,
False,3.87,2636.5,1424.95,499.43,206864.41
True,3.82,2562.6,1477.77,510.02,206007.28

In [49]:
housing["bedrooms_missing"].value_counts()

bedrooms_missing
False    20433
True       207
Name: count, dtype: int64

<h3 align="center" style="color: rgb(6, 165, 245);"><b>ANALYSIS REPORT</b></h3>

<p style="text-align: justify; font-family: sans-serif; line-height: 1.6;">
    <b>1. Problem definition</b><br>
    We have a supervised regression task. The objective is to predict the median house value of a California census block group using the available demographic, geographic, and housing features.<br><br>
    <b>2. Dataset structure</b><br>
    The dataset contains 20,640 observations and 10 columns: nine potential predictors and one target.<br><br>
    <b>3. Feature types</b><br>
    Numerical: longitude, latitude, housing age, rooms, bedrooms, population, households, and median income.<br>
    Categorical: ocean_proximity.<br>
    Target: median_house_value, a numerical variable.<br><br>
    <b>4. Data completeness</b><br>
    total_bedrooms contains 207 missing entries, approximately 1.003% of all rows. We should investigate and choose an appropriate imputation strategy rather than automatically dropping rows.<br><br>
    <b>5. Duplicate records</b><br>
    The initial check found zero exact duplicate rows. This is useful, although it doesn't guarantee there are no other data-quality problems.<br><br>
    <b>6. Model feasibility</b><br>
    Linear regression is a reasonable first baseline. The categorical feature will need suitable encoding, and the numerical features may benefit from further investigation and preprocessing.<br><br>
    <b>7. Remaining uncertainty</b><br>
    We haven't yet established the distributions of individual features, the presence of influential observations, relationships with house value, or whether the data contains unusual target values. Those questions belong to subsequent EDA stages.
</p>